[package]
name = "wgpu_learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.13"
env_logger = "0.9"
winit = "0.27"
log = "0.4"
anyhow = "1"